services:
  # Backend API service
  - type: web
    name: fairwaylive-api
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: fairwaylive-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: fairwaylive-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false # Set in Render dashboard
    
  # Redis for real-time features
  - type: redis
    name: fairwaylive-redis
    region: oregon
    plan: free

databases:
  # PostgreSQL database
  - name: fairwaylive-db
    region: oregon
    plan: free
    databaseName: fairwaylive
    user: fairwaylive